### ISSUE TITLE
How can I use it?

### ISSUE THREAD

**Issue by AngelSeed** [FPC-PM/NameplateSignResizer#1]
I want to use this Pligins,
How should I put it in?

**Comment by FPC-PM** [comment]
The plugin is still under testing to be added to the Dalamud plugin list, but I could push an early release dll if in a few hours of you want to try it out now . You would need to take that dll and add it as a dev plugin. 

Just be aware that there are still some bugs to work out. It behaves as expected in instanced content, but may act weird elsewhere.

**Comment by AngelSeed** [comment]
Thanks for the reply!
I don't know how to build it, so I'm waiting patiently.
